apiVersion: v1
kind: PersistentVolume
metadata: 
  name: db-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: "/home/ubuntu/pv-data"

